[[ ${FILE_SETTINGS__DRIVER_NAME} != "local" ]] || echo "WARNING! Files are being are being stored on disk and will be wiped periodically. This means anything you upload to Mattemost will disappear. For non-preview instances, please use Amazon S3 or install a production setup https://www.mattermost.org/installation/"


export SERVICE_SETTINGS__SITEURL=${SERVICE_SETTINGS__SITEURL:=""}

export FILE_SETTINGS__DRIVER_NAME=${FILE_SETTINGS__DRIVER_NAME:="local"}
export FILE_SETTINGS__AMAZON_S3_ACCESS_KEY_ID=${FILE_SETTINGS__AMAZON_S3_ACCESS_KEY_ID:=""}
export FILE_SETTINGS__AMAZON_S3_SECRET_ACCESS_KEY=${FILE_SETTINGS__AMAZON_S3_SECRET_ACCESS_KEY:=""}
export FILE_SETTINGS__AMAZON_S3_BUCKET=${FILE_SETTINGS__AMAZON_S3_BUCKET:=""}
export FILE_SETTINGS__AMAZON_S3_REGION=${FILE_SETTINGS__AMAZON_S3_REGION:=""}

export EMAIL_SETTINGS__SEND_EMAIL_NOTIFICATIONS=${EMAIL_SETTINGS__SEND_EMAIL_NOTIFICATIONS:=false}
export EMAIL_SETTINGS__REQUIRE_EMAIL_VERIFICATION=${EMAIL_SETTINGS__REQUIRE_EMAIL_VERIFICATION:=false}
export EMAIL_SETTINGS__FEEDBACK_NAME=${EMAIL_SETTINGS__FEEDBACK_NAME:=""}
export EMAIL_SETTINGS__FEEDBACK_EMAIL=${EMAIL_SETTINGS__FEEDBACK_EMAIL:=""}
export EMAIL_SETTINGS__FEEDBACK_ORGANIZATION=${EMAIL_SETTINGS__FEEDBACK_ORGANIZATION:=""}
export EMAIL_SETTINGS__SMTP_AUTH_ENABLED=${EMAIL_SETTINGS__SMTP_AUTH_ENABLED:=false}
export EMAIL_SETTINGS__SMTP_USERNAME=${EMAIL_SETTINGS__SMTP_USERNAME:=""}
export EMAIL_SETTINGS__SMTP_PASSWORD=${EMAIL_SETTINGS__SMTP_PASSWORD:=""}
export EMAIL_SETTINGS__SMTP_SERVER=${EMAIL_SETTINGS__SMTP_SERVER:=""}
export EMAIL_SETTINGS__SMTP_PORT=${EMAIL_SETTINGS__SMTP_PORT:=""}
export EMAIL_SETTINGS__CONNECTION_SECURITY=${EMAIL_SETTINGS__CONNECTION_SECURITY:=""}

export EMAIL_SETTINGS__SEND_PUSH_NOTIFICATIONS=${EMAIL_SETTINGS__SEND_PUSH_NOTIFICATIONS:=false}
export EMAIL_SETTINGS__PUSH_NOTIFICATION_SERVER=${EMAIL_SETTINGS__PUSH_NOTIFICATION_SERVER:=""}
export EMAIL_SETTINGS__PUSH_NOTIFICATION_CONTENTS=${EMAIL_SETTINGS__PUSH_NOTIFICATION_CONTENTS:="generic"}


export SESSION_LENGTH__WEB=${SESSION_LENGTH__WEB:=30}
export SESSION_LENGTH__MOBILE=${SESSION_LENGTH__MOBILE:=30}
export SESSION_LENGTH__SSO=${SESSION_LENGTH__SSO:=30}

lib/envsubst < config/config-heroku-template.json > config/config-heroku.json

bin/mattermost --config=config/config-heroku.json
