[[ ${FILE_SETTINGS__DRIVER_NAME} != "local" ]] || echo "WARNING! Files are being are being stored on disk and will be wiped periodically. This means anything you upload to Mattemost will disappear. For non-preview instances, please use Amazon S3 or install a production setup https://www.mattermost.org/installation/"


export SERVICE_SETTINGS__SITEURL=${SERVICE_SETTINGS__SITEURL:=""}

export FILE_SETTINGS__DRIVER_NAME=${FILE_SETTINGS__DRIVER_NAME:="local"}
export FILE_SETTINGS__AMAZON_S3_ACCESS_KEY_ID=${FILE_SETTINGS__AMAZON_S3_ACCESS_KEY_ID:=""}
export FILE_SETTINGS__AMAZON_S3_SECRET_ACCESS_KEY=${FILE_SETTINGS__AMAZON_S3_SECRET_ACCESS_KEY:=""}
export FILE_SETTINGS__AMAZON_S3_BUCKET=${FILE_SETTINGS__AMAZON_S3_BUCKET:=""}
export FILE_SETTINGS__AMAZON_S3_REGION=${FILE_SETTINGS__AMAZON_S3_REGION:=""}

export LINK_PREVIEW__ENABLE=${LINK_PREVIEW__ENABLE:=false}

export EMAIL_SETTINGS__SEND_EMAIL_NOTIFICATIONS=${EMAIL_SETTINGS__SEND_EMAIL_NOTIFICATIONS:=false}
export EMAIL_SETTINGS__REQUIRE_EMAIL_VERIFICATION=${EMAIL_SETTINGS__REQUIRE_EMAIL_VERIFICATION:=false}
export EMAIL_SETTINGS__FEEDBACK_NAME=${EMAIL_SETTINGS__FEEDBACK_NAME:=""}
export EMAIL_SETTINGS__FEEDBACK_EMAIL=${EMAIL_SETTINGS__FEEDBACK_EMAIL:=""}
export EMAIL_SETTINGS__FEEDBACK_ORGANIZATION=${EMAIL_SETTINGS__FEEDBACK_ORGANIZATION:=""}
export EMAIL_SETTINGS__SMTP_AUTH_ENABLED=${EMAIL_SETTINGS__SMTP_AUTH_ENABLED:=false}
export EMAIL_SETTINGS__SMTP_USERNAME=${EMAIL_SETTINGS__SMTP_USERNAME:=""}
export EMAIL_SETTINGS__SMTP_PASSWORD=${EMAIL_SETTINGS__SMTP_PASSWORD:=""}
export EMAIL_SETTINGS__SMTP_SERVER=${EMAIL_SETTINGS__SMTP_SERVER:=""}
export EMAIL_SETTINGS__SMTP_PORT=${EMAIL_SETTINGS__SMTP_PORT:=""}
export EMAIL_SETTINGS__CONNECTION_SECURITY=${EMAIL_SETTINGS__CONNECTION_SECURITY:=""}

export EMAIL_SETTINGS__SEND_PUSH_NOTIFICATIONS=${EMAIL_SETTINGS__SEND_PUSH_NOTIFICATIONS:=false}
export EMAIL_SETTINGS__PUSH_NOTIFICATION_SERVER=${EMAIL_SETTINGS__PUSH_NOTIFICATION_SERVER:=""}
export EMAIL_SETTINGS__PUSH_NOTIFICATION_CONTENTS=${EMAIL_SETTINGS__PUSH_NOTIFICATION_CONTENTS:="generic"}


export SESSION_LENGTH__WEB=${SESSION_LENGTH__WEB:=30}
export SESSION_LENGTH__MOBILE=${SESSION_LENGTH__MOBILE:=30}
export SESSION_LENGTH__SSO=${SESSION_LENGTH__SSO:=30}

export GOOGLE_SETTINGS__ENABLE=${GOOGLE_SETTINGS__ENABLE:=false}
export GOOGLE_SETTINGS__SECRET=${GOOGLE_SETTINGS__SECRET:=""}
export GOOGLE_SETTINGS__ID=${GOOGLE_SETTINGS__ID:=""}
export GOOGLE_SETTINGS__SCOPE=${GOOGLE_SETTINGS__SCOPE:="profile email"}
export GOOGLE_SETTINGS__AUTH_ENDPOINT=${GOOGLE_SETTINGS__AUTH_ENDPOINT:="https://accounts.google.com/o/oauth2/v2/auth"}
export GOOGLE_SETTINGS__TOKEN_ENDPOINT=${GOOGLE_SETTINGS__TOKEN_ENDPOINT:="https://www.googleapis.com/oauth2/v4/token"}
export GOOGLE_SETTINGS__USER_ENDPOINT=${GOOGLE_SETTINGS__USER_ENDPOINT:="https://people.googleapis.com/v1/people/me?personFields=names,emailAddresses,nicknames,metadata"}

export PICKER_GFYCAT__ENABLE=${PICKER_GFYCAT__ENABLE:=false}

export PICKER_GFYCAT__API_KEY=${PICKER_GFYCAT__API_KEY:=""}
export PICKER_GFYCAT__API_SECRET=${PICKER_GFYCAT__API_SECRET:=""}
export CUSTOM_EMOJI__ENABLE=${CUSTOM_EMOJI_ENABLE:=true}
export CUSTOM_EMOJI__ENABLE=${ENABLE_EMOJI_PICKER:=true}
export PLUGIN_GIPHY__ENABLE=${PLUGIN_GIPHY__ENABLE:=false}

export PLUGIN_GIPHY__PROVIDER=${PLUGIN_GIPHY__PROVIDER:="giphy"}
export PLUGIN_GIPHY__APIKEY=${PLUGIN_GIPHY__APIKEY:=""}
export PLUGIN_GIPHY__LANGUAGE=${PLUGIN_GIPHY__LANGUAGE:="en"}
export PLUGIN_GIPHY__RATING=${PLUGIN_GIPHY__RATING:=""}
export PLUGIN_GIPHY__RENDITION=${PLUGIN_GIPHY__RENDITION:="fixed_height_small"}
export PLUGIN_GIPHY__RENDITIONGFYCAT=${PLUGIN_GIPHY__RENDITIONGFYCAT:="100pxGif"}


lib/envsubst < config/config-heroku-template.json > config/config-heroku.json

bin/mattermost --config=config/config-heroku.json
